<?php
/**
 * Generated by Luis M. Segundo 
 */
 
// Arreglo de tipo clave valor
$colores = array(
	'green'=>'Verde',
	'red'=>'Rojo',
	'blue'=>'Azul',
	'yellow'=>'Amarillo',
	'purple'=>'Morado'
	);
 ?>
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>Fondo Dinamico</title>
	<script>
		function changeBackground(color){
			document.body.style.background=color;
		}

		function changeOriginal(){
			document.body.style.background="white";
		}
	</script>
</head>
<body>
<h1>Cambiar Fondo</h1>
	<select name="colores" id="colores" 
	onchange="changeBackground(this.value)">
	    <option value="">Seleccione un Color</option>
		<?php foreach ($colores as $key => $value) { ?>
				<option value="<?=$key?>"><?=$value?></option>
		<?php } ?>
	</select>

	<input type="button" value="resetear" onclick="changeOriginal()">
</body>
</html>
